### ISSUE TITLE
Hope to see `format on save` feature for CUE

### ISSUE THREAD

**Issue by wonderflow** [cue-sh/vscode-cue#17]
vscode format on save for `.cue` extension

**Comment by myitcv** [comment]
Hi @wonderflow! This will land automatically via https://github.com/cue-lang/cue/issues/142. On the basis I will close this issue and people can follow along there.

**Comment by johnallen3d** [comment]
@wonderflow — https://github.com/cue-sh/vscode-cue/issues/11#issuecomment-998070357
